Traceback (most recent call last):
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Subset "Sreepur" data
sreepur_data = vector_data[vector_data['NAME'] == 'Sreepur']

# View the subset
print(kanchanpur_data.head())

# Plot the subsetted data
import matplotlib.pyplot as plt

sreepur_data.plot(column='NAME', cmap='viridis', legend=False)
plt.title("Sreepur VDC, Nepal")
plt.show()

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<module>[1;34m[0m
[0;32m      2[0m sreepur_data [38;5;241m=[39m vector_data[vector_data[[38;5;124m'[39m[38;5;124mNAME[39m[38;5;124m'[39m] [38;5;241m==[39m [38;5;124m'[39m[38;5;124mSreepur[39m[38;5;124m'[39m]
[0;32m      4[0m [38;5;66;03m# View the subset[39;00m
[1;32m----> 5[0m [38;5;28mprint[39m([43mkanchanpur_data[49m[38;5;241m.[39mhead())
[0;32m      7[0m [38;5;66;03m# Plot the subsetted data[39;00m
[0;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

[1;31mNameError[0m: name 'kanchanpur_data' is not defined
NameError: name 'kanchanpur_data' is not defined

