Traceback (most recent call last):
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\ombha\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Reproject both geometries to a projected CRS (e.g., EPSG:3395 for meters)
sreepur_data_projected = sreepur_data.to_crs(epsg=32645)
tribhuwanbasti_projected = tribhuwan_data.to_crs(epsg=32645)

# Compute the distance between the two polygons
distance = sreepur_data_projected.geometry.distance(tribhuwan_data_projected.geometry.iloc[0]).min()

# Output the calculated distance
print(f"Distance between Sreepur and Tribhuwanbasti is: {distance:.2f} meters")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [15][0m, in [0;36m<module>[1;34m[0m
[0;32m      3[0m tribhuwanbasti_projected [38;5;241m=[39m tribhuwan_data[38;5;241m.[39mto_crs(epsg[38;5;241m=[39m[38;5;241m32645[39m)
[0;32m      5[0m [38;5;66;03m# Compute the distance between the two polygons[39;00m
[1;32m----> 6[0m distance [38;5;241m=[39m sreepur_data_projected[38;5;241m.[39mgeometry[38;5;241m.[39mdistance([43mtribhuwan_data_projected[49m[38;5;241m.[39mgeometry[38;5;241m.[39miloc[[38;5;241m0[39m])[38;5;241m.[39mmin()
[0;32m      8[0m [38;5;66;03m# Output the calculated distance[39;00m
[0;32m      9[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mDistance between Sreepur and Tribhuwanbasti is: [39m[38;5;132;01m{[39;00mdistance[38;5;132;01m:[39;00m[38;5;124m.2f[39m[38;5;132;01m}[39;00m[38;5;124m meters[39m[38;5;124m"[39m)

[1;31mNameError[0m: name 'tribhuwan_data_projected' is not defined
NameError: name 'tribhuwan_data_projected' is not defined

